// <auto-generated />
namespace CheckoutAppDomain.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Correcting_category_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Correcting_category_name));
        
        string IMigrationMetadata.Id
        {
            get { return "201810151511426_Correcting_category_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
